'use client';

import { useDroppable } from '@dnd-kit/core';
import { SortableContext, verticalListSortingStrategy, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { useTranslations } from 'next-intl';
import { QRCodeSVG } from 'qrcode.react';
import { DotsVertical, X } from '@untitledui/icons';
import { cx } from '@/utils/cx';
import type { TemplateElement, PrintTemplateDesign } from '@/types/print-template';
import { renderPreview } from '../utils/preview-renderer';

/** Tiny CSS-only Code128-ish barcode preview (pure visual approximation; the real
 *  barcode is generated by the printer agent at print time). */
function BarcodePreview({ value }: { value: string }) {
  // Deterministic pattern from the value so the same id always looks the same.
  const bars: number[] = [];
  for (let i = 0; i < value.length; i++) {
    bars.push((value.charCodeAt(i) % 4) + 1);
    bars.push(((value.charCodeAt(i) >> 2) % 3) + 1);
  }
  // Pad to a minimum number of bars so short values still feel like barcodes.
  while (bars.length < 28) bars.push(((bars.length * 7) % 4) + 1);
  return (
    <div style={{ display: 'flex', alignItems: 'flex-end', gap: '1px', height: 36 }}>
      {bars.map((width, i) => (
        <div
          key={i}
          style={{
            width: `${width}px`,
            height: '100%',
            background: i % 2 === 0 ? '#111' : 'transparent',
          }}
        />
      ))}
    </div>
  );
}

interface ReceiptCanvasProps {
  design: PrintTemplateDesign;
  selectedElementId: string | null;
  onSelectElement: (id: string | null) => void;
  onRemoveElement: (id: string) => void;
}

function SortableCanvasElement({
  element,
  previewLines,
  isSelected,
  onSelect,
  onRemove,
  cols,
}: {
  element: TemplateElement;
  previewLines: { text: string; bold?: boolean; big?: boolean; align?: string; isSpecial?: boolean; isQrCode?: boolean; isBarcode?: boolean; barcodeValue?: string }[];
  isSelected: boolean;
  onSelect: () => void;
  onRemove: () => void;
  cols: number;
}) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: element.id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      className={cx(
        'group relative',
        isDragging && 'z-10 opacity-70',
      )}
    >
      {/* Selection border + controls */}
      <div
        className={cx(
          'relative rounded border transition-colors cursor-pointer',
          isSelected
            ? 'border-brand-solid bg-brand-secondary/30'
            : 'border-transparent hover:border-secondary',
        )}
        onClick={(e) => { e.stopPropagation(); onSelect(); }}
      >
        {/* Drag handle + remove button — handle stays visible so it's always
            grabbable; emphasises on hover/selection. */}
        <div className={cx(
          'absolute -left-5 top-0 flex flex-col items-center gap-0.5 opacity-40 transition-opacity',
          'group-hover:opacity-100',
          isSelected && 'opacity-100',
        )}>
          <button
            type="button"
            className="cursor-grab rounded p-0.5 text-quaternary hover:text-tertiary active:cursor-grabbing"
            {...attributes}
            {...listeners}
          >
            <DotsVertical className="h-3.5 w-3.5" />
          </button>
          <button
            type="button"
            onClick={(e) => { e.stopPropagation(); onRemove(); }}
            className="rounded p-0.5 text-quaternary hover:text-error-primary"
          >
            <X className="h-3 w-3" />
          </button>
        </div>

        {/* Preview lines */}
        <div className="px-1">
          {previewLines.map((line, i) => {
            if (line.isQrCode) {
              return (
                <div key={i} className="flex justify-center py-2">
                  <QRCodeSVG value="https://openeos.de" size={64} />
                </div>
              );
            }

            if (line.isBarcode) {
              return (
                <div key={i} className="flex flex-col items-center gap-1 py-2">
                  <BarcodePreview value={line.barcodeValue || '0000'} />
                  <span style={{ fontFamily: 'monospace', fontSize: '10px', letterSpacing: '0.05em', color: '#444' }}>
                    {line.barcodeValue}
                  </span>
                </div>
              );
            }

            if (line.isSpecial) {
              return (
                <div
                  key={i}
                  className="text-center text-[10px] italic text-quaternary"
                  style={{ fontFamily: 'monospace' }}
                >
                  {line.text}
                </div>
              );
            }

            const fontSize = line.big ? '16px' : '12px';
            let textAlign: 'left' | 'center' | 'right' = 'left';
            if (line.align === 'center') textAlign = 'center';
            if (line.align === 'right') textAlign = 'right';

            return (
              <div
                key={i}
                className={cx(
                  'whitespace-pre-wrap leading-tight',
                  line.bold && 'font-bold',
                )}
                style={{
                  fontFamily: 'monospace',
                  fontSize,
                  textAlign,
                }}
              >
                {line.text || '\u00A0'}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

export function ReceiptCanvas({
  design,
  selectedElementId,
  onSelectElement,
  onRemoveElement,
}: ReceiptCanvasProps) {
  const t = useTranslations('printTemplates.designer');
  const cols = design.paperWidth === 80 ? 42 : 32;

  const { setNodeRef, isOver } = useDroppable({
    id: 'canvas-drop-zone',
  });

  // Group preview lines by element
  const allPreviewLines = renderPreview(design);
  const elementPreviewMap = new Map<string, typeof allPreviewLines>();
  for (const line of allPreviewLines) {
    const existing = elementPreviewMap.get(line.elementId) || [];
    existing.push(line);
    elementPreviewMap.set(line.elementId, existing);
  }

  return (
    <div className="flex h-full flex-col overflow-hidden">
      <div className="border-b border-secondary px-4 py-3">
        <h3 className="text-sm font-semibold text-primary">{t('canvas')}</h3>
      </div>
      <div
        className="flex-1 overflow-y-auto p-4"
        style={{
          background:
            'repeating-linear-gradient(45deg, rgba(20,20,20,0.018) 0 6px, transparent 6px 12px), color-mix(in oklab, var(--ink) 4%, transparent)',
        }}
        onClick={() => onSelectElement(null)}
      >
        <div className="mx-auto flex justify-center">
          {/* Receipt paper — visual width matches real thermal paper proportions
              (80mm ≈ 360px, 58mm ≈ 260px on a typical screen). The font scale is
              tuned so 42 monospace cols (80mm spec) fit without clipping. */}
          <div
            ref={setNodeRef}
            className={cx(
              'relative bg-white pl-6 pr-3 py-4 transition-colors',
              isOver && 'ring-2 ring-brand-solid',
            )}
            style={{
              width: design.paperWidth === 80 ? '360px' : '260px',
              minHeight: '400px',
              fontFamily: 'monospace',
              color: '#1a1a1a',
              backgroundImage:
                'repeating-linear-gradient(0deg, rgba(0,0,0,0.012) 0 1px, transparent 1px 2px), linear-gradient(180deg, #fdfcf8 0%, #f7f5ee 100%)',
              boxShadow:
                '0 18px 40px rgba(20,18,12,0.10), 0 4px 12px rgba(20,18,12,0.06), inset 0 1px 0 rgba(255,255,255,0.7)',
              // Torn top + bottom edges (zigzag) using SVG mask
              WebkitMaskImage:
                'url("data:image/svg+xml;utf8,<svg xmlns=\\\'http://www.w3.org/2000/svg\\\' width=\\\'14\\\' height=\\\'10\\\' viewBox=\\\'0 0 14 10\\\'><polygon points=\\\'0,0 14,0 14,4 7,7 0,4\\\' fill=\\\'%23000\\\'/></svg>"), linear-gradient(black, black), url("data:image/svg+xml;utf8,<svg xmlns=\\\'http://www.w3.org/2000/svg\\\' width=\\\'14\\\' height=\\\'10\\\' viewBox=\\\'0 0 14 10\\\'><polygon points=\\\'0,6 7,3 14,6 14,10 0,10\\\' fill=\\\'%23000\\\'/></svg>")',
              WebkitMaskRepeat: 'repeat-x, no-repeat, repeat-x',
              WebkitMaskSize: 'auto 10px, 100% calc(100% - 18px), auto 10px',
              WebkitMaskPosition: 'top, center, bottom',
              WebkitMaskComposite: 'source-over' as React.CSSProperties['WebkitMaskComposite'],
              maskRepeat: 'repeat-x, no-repeat, repeat-x',
              maskSize: 'auto 10px, 100% calc(100% - 18px), auto 10px',
              maskPosition: 'top, center, bottom',
            }}
            onClick={() => onSelectElement(null)}
          >
            {design.elements.length === 0 ? (
              <div className="flex h-full min-h-[300px] items-center justify-center">
                <p className="text-sm text-gray-400 italic">{t('dragHint')}</p>
              </div>
            ) : (
              <SortableContext
                items={design.elements.map((el) => el.id)}
                strategy={verticalListSortingStrategy}
              >
                {design.elements.map((element) => (
                  <SortableCanvasElement
                    key={element.id}
                    element={element}
                    previewLines={elementPreviewMap.get(element.id) || []}
                    isSelected={selectedElementId === element.id}
                    onSelect={() => onSelectElement(element.id)}
                    onRemove={() => onRemoveElement(element.id)}
                    cols={cols}
                  />
                ))}
              </SortableContext>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
